

public enum EventID{
    //None = 0,
    OnChangeAnimPlayer,
    OnChangeSkin,
    OnUpdateUISkin,
    UpgradeStats,
    ActionShowMiniGame,
    OnChangeLaguage,
    OnChangeFont,
    OnShowUIAction,
    OnShowUIMachine,
    OnShowUIOder,
    OnShowUICustomer,
    OnShowUIStorage,
    OnShowUITree,
    OnShowLoading,
    OnChangeGold,
    OnChangeGem,
    OnChangeExp,
    OnLevelUp,
    OnChangeProduct,
    ViewCameraFollowName,
    OnBuyMoreProduct,
    OnChangeMainUI,
    OnShowUIDeco,
    OnChangeDeco,
    OnChangeTutorial,
    OnAnimationEndLoading,
    OnRewardGem,
    OnRewardGold,
    OnUpdateMission,
    OnChangeScene
}
